### ISSUE TITLE
Produce/Consume different topics?

### ISSUE THREAD

**Issue by darrenfurr** [fmannhardt/graphql-kafka-subscriptions#4]
Felix,

Thank you for updating/maintaining this library? Can it be configured to produce/consume to different topics?

Maybe through using worker_threads in nodeJS? 

Thoughts?

**Comment by 0xE282B0** [comment]
Hi,

I would love to subscribe to multiple Kafka topics too. A good fit could be using the channel as topic when starting a subscription. But if I get the code right, the channel is used to split the single topic into multiple virtual channels via the event emitter. What I'm searching for is more like "Kafka over GraphQL".

Therefore my approach would be a breaking change. 

More Thoughts?
